<?php

/**
 * @file
 */

use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 *
 * This function name has the format {MODULE_NAME}_migrate_{MIGRATION_ID}_prepare_row.
 */
function d7_post_migrate_migrate_d7_node_post_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {

  # varies
  $values = $row->getSourceProperty('field_parts');
  $value_new = [];
  if ($values) {
    foreach ($values as $value) {
      $value_new[] = ['item_id' => $value['value']];
    }
    $row->setSourceProperty('field_parts', $value_new);
  }

  return $row;
}
